# Dependencies
markdown:         kramdown


# Permalinks
permalink:        pretty

# Setup
title:            Anirudh Maiya
tagline:          Anirudh Maiya
description:      ''
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           Anirudh Maiya

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag